#!name=高德地图去广告（保留足迹）
#!desc=移除高德地图广告，保留“足迹”功能
#!author=xchun5678

[Script]
# 移除启动广告
http-response ^https?:\/\/.*amap.com\/ws\/faas\/ads\/config\/channel\? url reject-200
http-response ^https?:\/\/.*amap.com\/ws\/shield\/search\/hotwords url reject-200
http-response ^https?:\/\/.*amap.com\/ws\/searchbox\/faas\/recommend\/words url reject-200
http-response ^https?:\/\/.*amap.com\/ws\/searchbox\/suggest\/list url reject-200

# 关键词广告（如底部横幅、推荐）
http-response ^https?:\/\/.*amap.com\/ws\/valueadded\/recommend\/ad url reject-200
http-response ^https?:\/\/.*amap.com\/ws\/valueadded\/advertisement\/recommend url reject-200
http-response ^https?:\/\/.*amap.com\/ws\/promotion\/activity\/ad url reject-200

# 去除高德地图首页推荐模块广告（非足迹）
http-response ^https?:\/\/.*amap.com\/ws\/searchbox\/faas\/recommend\/popup url reject-200

[MITM]
hostname = *.amap.com
